export const LOADING_OBEDIENCELIST = 'OBEDIENCE/LOADING_OBEDIENCELIST'
export const SUCCESS_OBEDIENCELIST = 'OBEDIENCE/SUCCESS_OBEDIENCELIST'
export const ERROR_OBEDIENCELIST = 'OBEDIENCE/ERROR_OBEDIENCELIST'
