export const LOADING_STEP_COMPLETED = 'QUIZ/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'QUIZ/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'QUIZ/ERROR_STEP_COMPLETED'
