export const LOADING_STEP_COMPLETED = 'EXERCISE/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'EXERCISE/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'EXERCISE/ERROR_STEP_COMPLETED'
