export const LOADING_STEP_COMPLETED = 'SLIDE/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'SLIDE/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'SLIDE/ERROR_STEP_COMPLETED'
