export const LOADING_STEP_COMPLETED = 'FEEDBACK/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'FEEDBACK/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'FEEDBACK/ERROR_STEP_COMPLETED'
