export const LOADING_STEP_COMPLETED = 'VIDEO/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'VIDEO/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'VIDEO/ERROR_STEP_COMPLETED'
