export const LOADING_STEP_COMPLETED = 'QUESTION/LOADING_STEP_COMPLETED'
export const SUCCESS_STEP_COMPLETED = 'QUESTION/SUCCESS_STEP_COMPLETED'
export const ERROR_STEP_COMPLETED = 'QUESTION/ERROR_STEP_COMPLETED'
