export const SET_USER = "AUTH/SET_USER";
export const SET_TOKEN = "AUTH/SET_TOKEN";
export const SET_MODALNOTLOGGED = "AUTH/SET_MODALNOTLOGGED";
export const SET_MODALRESPONSEUSER = "AUTH/SET_MODALRESPONSEUSER";
export const SET_MODALERRORSERVER = "AUTH/SET_MODALERRORSERVER";
