export const SET_HAS_HEADER = 'TRAINING/SET_HAS_HEADER'
export const SET_HAS_FOOTER = 'TRAINING/SET_HAS_FOOTER'
export const SET_LOADINGPETS = 'TRAINING/SET_LOADINGTRAINING'
export const SET_PETSLIST = 'TRAINING/SET_PETSTRAINING'
