export const SET_HAS_HEADER = 'TRAINING/SET_HAS_HEADER'
export const SET_HAS_FOOTER = 'TRAINING/SET_HAS_FOOTER'
export const SET_LOADINGTRAINING = 'TRAINING/SET_LOADINGTRAINING'
export const SET_TRAININGLIST = 'TRAINING/SET_PETSTRAINING'
